name: Sync with upstream main-ge

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-upstream:
    runs-on: xcosimnow01-XRT_aiebu
    
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3
      with:
        ref: main-ge

    - name: Set up upstream repo
      run: |
        # add remote if necessary
        if git remote | grep -1 "^ghec$"; then
          echo "ghec remote exists"
        else
          echo "ghec remote does not exist"
          git remote add ghec https://github.com/Xilinx/aiebu.git
        fi
        if git remote | grep -1 "^ghes$"; then
          echo "ghes remote exists"
        else
          echo "ghes remote does not exist"
          git remote add ghes https://gitenterprise.xilinx.com/XRT/aiebu.git
        fi

    - name: Merge changes from upstream to main-ge branch
      run: |
        git fetch ghec
        git reset --hard ghec/main-ge

    - name: Force push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push --force ghes main-ge
