name: Sync with upstream main-ge

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-upstream:
    runs-on: xcosimnow01-XRT_aiebu
    
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Set up upstream repo
      run: |
        git remote add ghec https://github.com/Xilinx/aiebu.git
        git fetch ghec

    - name: Merge changes from upstream to main-ge branch
      run: |
        git checkout --track origin/main-ge
        git reset --hard ghec/main-ge

    - name: Force push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push --force origin main-ge
